from django import forms
from django.http import HttpResponse, FileResponse
from django.template import loader
from django.shortcuts import redirect, render
from django.urls import reverse
from django.contrib import messages
from django.utils.text import slugify
import os
import sys
import json
import logging
import logging.handlers
import logging.config
import re
from talkingscores.settings import BASE_DIR, MEDIA_ROOT
from lib.midiHandler import *
from datetime import datetime
import zipfile
from io import BytesIO

from lib.talkingscoreslib import Music21TalkingScore
from talkingscoresapp.models import TSScore, TSScoreState

# MIDI utilities for standalone download
from lib.midi_utils import collect_score_midi_files, generate_midi_mapping_script
from jinja2 import Environment, FileSystemLoader

from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
import smtplib

logger = logging.getLogger("TSScore")



def download_standalone_score(request, id, filename):
    """
    Generate and download a self-contained HTML talking score with embedded MIDI files.
    This creates a single HTML file that works offline on any device, perfect for mobile use.
    """
    try:
        # Create the score object
        score_obj = TSScore(id=id, filename=filename)
        
        if score_obj.state() == TSScoreState.AWAITING_OPTIONS:
            messages.error(request, "Please configure your talking score options first.")
            return redirect('options', id, filename)
        elif score_obj.state() == TSScoreState.FETCHING:
            messages.error(request, "The requested score could not be found. It may have expired.")
            return redirect('index')
        
        # Get the score directory and MIDI output path
        score_directory = os.path.join(MEDIA_ROOT, id)
        web_path = f"/midis/{id}/{filename}"
        
        # Ensure all MIDI files are generated by getting the HTML first
        # This triggers MIDI generation if needed
        logger.info(f"Ensuring MIDI files are generated for standalone download: {id}/{filename}")
        try:
            score_obj.html()  # This generates all MIDI files
        except Exception as e:
            logger.error(f"Error generating score HTML for MIDI creation: {e}")
            # Continue anyway, we might have some MIDI files
        
        # Collect and embed all MIDI files
        logger.info(f"Collecting MIDI files from: {score_directory}")
        midi_files = collect_score_midi_files(score_directory)
        
        if not midi_files:
            logger.warning(f"No MIDI files found for score {id}/{filename}")
            messages.warning(request, "No MIDI files found. The standalone score may not have audio playback.")
        
        # Generate the MIDI mapping JavaScript
        embedded_midi_script = generate_midi_mapping_script(midi_files, web_path)
        
        # Generate the standalone HTML content
        standalone_html = generate_standalone_html(score_obj, embedded_midi_script, id, filename)

        # Log file size for monitoring
        file_size_kb = len(standalone_html.encode('utf-8')) / 1024
        file_size_mb = file_size_kb / 1024

        # Create the response with the HTML file
        response = HttpResponse(standalone_html, content_type='text/html; charset=utf-8')

        # Create a safe filename for download
        score_info = score_obj.info()
        logger.info(f"Score info title: {score_info.get('title')}")
        safe_title = score_info.get('title', 'Talking Score').replace(' ', '_')
        logger.info(f"After replacing spaces: {safe_title}")
        safe_title = ''.join(c for c in safe_title if c.isalnum() or c in ('_', '-'))
        logger.info(f"After sanitization: {safe_title}")
        download_filename = f"{safe_title}_standalone.html"
        logger.info(f"Final download filename: {download_filename}")

        response['Content-Disposition'] = f'attachment; filename="{download_filename}"'
        response['X-Robots-Tag'] = "noindex"

        # Log with file size information
        if file_size_mb >= 1:
            logger.info(f"Generated standalone talking score: {download_filename} ({file_size_mb:.2f} MB) with {len(midi_files)} embedded MIDI files")
        else:
            logger.info(f"Generated standalone talking score: {download_filename} ({file_size_kb:.1f} KB) with {len(midi_files)} embedded MIDI files")
        return response
        
    except Exception as e:
        logger.exception(f"Error generating standalone talking score for {id}/{filename}")
        messages.error(request, "An error occurred while generating the standalone talking score. Please try again.")
        return redirect('score', id, filename)


def generate_standalone_html(score_obj, embedded_midi_script, id, filename):
    """
    Generate standalone HTML by modifying the existing talking score HTML.
    This preserves all existing functionality while making it work offline.
    """
    try:
        # Get the original HTML content
        original_html = score_obj.html()
        
        # Get current timestamp for the standalone notice
        generation_timestamp = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
        
        # Start with the original HTML
        standalone_html = original_html
        logger.info(f"Original HTML length: {len(original_html)} characters")

        # 1. Remove the download section and its script
        # NOTE: The download section is NOT removed from standalone HTML to avoid regex issues.
        # The button will simply not work in the standalone version (can't download from a downloaded file).
        # This is acceptable since users can always regenerate from the original site.
        logger.info("Skipping download section removal to preserve HTML integrity")
        
        # 2. Add standalone notice after the <body> tag with proper CSS variable support
        standalone_notice = f'''
    <!-- Standalone Notice -->
    <div id="standalone-notice" style="
        background: var(--alert-warning-bg, #d1ecf1);
        border: 2px solid var(--alert-warning-border, #0c5460);
        border-radius: 8px;
        padding: 15px;
        margin: 20px;
        text-align: center;
        color: var(--alert-warning-color, #0c5460);
    ">
        <h3 style="margin: 0 0 10px 0; color: inherit;">📱 Offline Talking Score</h3>
        <p style="margin: 0; font-size: 14px; color: inherit;">
            This file works completely offline on any device!<br>
            Generated on {generation_timestamp} | All MIDI files embedded
        </p>
    </div>'''
        
        body_tag_pattern = r'(<body[^>]*>)'
        standalone_html = re.sub(body_tag_pattern, r'\1' + standalone_notice, standalone_html)
        
        # 3. Replace external CSS with embedded CSS
        css_link_pattern = r'<link href="http://127\.0\.0\.1:8000/static/css/talkingscores\.css" rel="stylesheet">'
        css_file_path = os.path.join(BASE_DIR, 'talkingscoresapp', 'static', 'css', 'talkingscores.css')
        
        try:
            with open(css_file_path, 'r', encoding='utf-8') as css_file:
                css_content = css_file.read()
            embedded_css = f'<style type="text/css">\n/* Embedded talkingscores.css */\n{css_content}\n</style>'
            standalone_html = re.sub(css_link_pattern, embedded_css, standalone_html)
        except FileNotFoundError:
            logger.warning(f"CSS file not found at {css_file_path}")
            # Remove the broken link
            standalone_html = re.sub(css_link_pattern, '', standalone_html)
        
        # 4. Add the embedded MIDI script after the MIDI.js include
        midi_js_pattern = r"(<script type='text/javascript' src='//www\.midijs\.net/lib/midi\.js'></script>)"
        midi_replacement = r'\1' + f'\n    <!-- Embedded MIDI files for offline use -->\n    <script>\n{embedded_midi_script}\n    </script>'
        standalone_html = re.sub(midi_js_pattern, midi_replacement, standalone_html)
        
        # 5. Fix the JavaScript to handle embedded MIDI properly
        original_js_pattern = r'<script>\s*document\.addEventListener\("DOMContentLoaded", \(event\) => \{.*?\}\);\s*</script>'
        
        # Parse the embedded MIDI script to extract the mapping
        midi_mapping = "const embeddedMidis = {};\n"
        if "embeddedMidis[" in embedded_midi_script:
            midi_mapping = "const embeddedMidis = {};\n" + embedded_midi_script
        
        new_js = f'''<script>
        document.addEventListener("DOMContentLoaded", (event) => {{
            // MIDI file mapping from embedded data
            {midi_mapping}
            
            function updateLink(link) {{
                const parentScope = link.closest('#global-controls, div[id^="segment-"]');
                if (!parentScope) return;
    
                const baseUrl = link.dataset.baseUrl;
                if (!baseUrl) return;
    
                const tempo = parentScope.querySelector('.ddlTempo').value;
                const click = parentScope.querySelector('.ddlClick').value;
    
                // Build the MIDI filename based on the original base URL
                let midiFilename;
                if (baseUrl.includes('/midis/')) {{
                    // Extract the base filename from the URL
                    const urlParts = baseUrl.split('/');
                    const baseFilename = urlParts[urlParts.length - 1].split('?')[0];
                    midiFilename = baseFilename + 'c' + click + 't' + tempo + '.mid';
                }} else {{
                    midiFilename = baseUrl.split('/').pop().split('?')[0] + 'c' + click + 't' + tempo + '.mid';
                }}
                
                let finalUrl;
                if (embeddedMidis[midiFilename]) {{
                    finalUrl = embeddedMidis[midiFilename];
                }} else {{
                    // Fallback to original URL with parameters
                    finalUrl = baseUrl + '&t=' + tempo + '&c=' + click;
                }}
                
                link.dataset.finalUrl = finalUrl;
            }}
    
            document.body.addEventListener('click', function(e) {{
                if (e.target.matches('.lnkPlay')) {{
                    e.preventDefault(); // Prevent default anchor behavior
                    e.stopPropagation(); // Stop event bubbling
                    
                    MIDIjs.stop(); // Ensure previous MIDI is stopped before playing new one
                    
                    updateLink(e.target); // Update the link just before playing
                    
                    const urlToPlay = e.target.dataset.finalUrl;
                    if (urlToPlay && urlToPlay !== 'undefined') {{
                        console.log('Playing MIDI (standalone):', urlToPlay.substring(0, 80) + '...');
                        MIDIjs.play(urlToPlay);
                    }} else {{
                        console.error("No valid final URL found for this link.", e.target);
                        console.log("Base URL:", e.target.dataset.baseUrl);
                        console.log("Available MIDI files:", Object.keys(embeddedMidis));
                    }}
                    return false; // Additional prevention of default behavior
                }}
            }});
    
            document.body.addEventListener('change', function(e) {{
                if (e.target.matches('.ddlTempo, .ddlClick')) {{
                    const changedElement = e.target;
                    
                    if (changedElement.closest('#global-controls')) {{
                        const isTempo = changedElement.matches('.ddlTempo');
                        const value = changedElement.value;
                        const selector = isTempo ? '.ddlTempo' : '.ddlClick';
                        document.querySelectorAll(selector).forEach(ddl => {{ ddl.value = value; }});
                    }}
    
                    document.querySelectorAll('.lnkPlay').forEach(updateLink);
                }}
            }});
    
            // Initial setup of all links
            document.querySelectorAll('.lnkPlay').forEach(updateLink);
            
            console.log('Standalone MIDI setup complete. Available files:', Object.keys(embeddedMidis).length);
        }});
        </script>'''
        
        # Replace the original JavaScript - find the last script tag in the document
        last_script_pattern = r'(<script>.*?document\.addEventListener\("DOMContentLoaded", \(\) => \{.*?\}\);.*?</script>)(?=\s*</body>)'
        standalone_html = re.sub(last_script_pattern, new_js, standalone_html, flags=re.DOTALL)
        
        # If that didn't work, try the main JS pattern
        if new_js not in standalone_html:
            standalone_html = re.sub(original_js_pattern, new_js, standalone_html, flags=re.DOTALL)
        
        # 6. Update the title to indicate it's standalone
        title_pattern = r'(<title>)(.*?)(</title>)'
        standalone_html = re.sub(title_pattern, r'\1\2 (Standalone)\3', standalone_html)
        
        return standalone_html
        
    except Exception as e:
        logger.error(f"Error generating standalone HTML: {e}")
        raise

class MusicXMLSubmissionForm(forms.Form):
    filename = forms.FileField(label='MusicXML file', widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'accept': '.xml,.musicxml,.mxl'}),
                               required=False)
    url = forms.URLField(label='URL to MusicXML file', widget=forms.URLInput(attrs={'class': 'form-control'}),
                         required=False)

    def clean_filename(self):
        uploaded_file = self.cleaned_data.get('filename')
        if uploaded_file:
            file_extension = os.path.splitext(uploaded_file.name)[1].lower()
            allowed_extensions = ['.xml', '.musicxml', '.mxl']
            if file_extension not in allowed_extensions:
                raise forms.ValidationError(
                    f"Invalid file type. Please upload a MusicXML file (.xml, .musicxml, or .mxl)."
                )
        return uploaded_file

    def clean(self):
        cleaned_data = super().clean()
        filename = cleaned_data.get("filename")
        url = cleaned_data.get("url")

        if not filename and not url:
            raise forms.ValidationError(
                "Please upload a MusicXML file or provide a URL.", code='required'
            )

        if filename and url:
            raise forms.ValidationError(
                "Please provide either a file or a URL, not both.", code='conflict'
            )

        return cleaned_data


class MusicXMLUploadForm(forms.Form):
    filename = forms.FileField(label='MusicXML file', widget=forms.ClearableFileInput(attrs={'class': 'form-control', 'accept': '.xml,.musicxml,.mxl'}))


class TalkingScoreGenerationOptionsForm(forms.Form):
    chk_playAll = forms.BooleanField(required=False)
    chk_playSelected = forms.BooleanField(required=False)
    chk_playUnselected = forms.BooleanField(required=False)
    chk_include_rests = forms.BooleanField(required=False)
    chk_include_ties = forms.BooleanField(required=False)
    chk_include_arpeggios = forms.BooleanField(required=False)
    chk_describe_chords = forms.BooleanField(required=False)
    

    bars_at_a_time = forms.ChoiceField(choices=(('1', 1), ('2', 2), ('4', 4), ('8', 8)), initial=4,
                                        label="Bars at a time")

    beat_division = forms.CharField(widget=forms.Select, required=False)

    pitch_description = forms.CharField(widget=forms.Select, required=False)
    rhythm_description = forms.CharField(widget=forms.Select, required=False)
    dot_position = forms.CharField(widget=forms.Select, required=False)
    rhythm_announcement = forms.CharField(widget=forms.Select, required=False)
    octave_description = forms.CharField(widget=forms.Select, required=False)
    octave_position = forms.CharField(widget=forms.Select, required=False)
    octave_announcement = forms.CharField(widget=forms.Select, required=False)

    chk_include_dynamics = forms.BooleanField(required=False)
    accidental_style = forms.CharField(widget=forms.Select, required=False)
    key_signature_accidentals = forms.CharField(widget=forms.Select, required=False)

    colour_position = forms.CharField(widget=forms.Select, required=False)
    chk_colourPitch = forms.BooleanField(required=False)
    chk_colourRhythm = forms.BooleanField(required=False)
    chk_colourOctave = forms.BooleanField(required=False)


class NotifyEmailForm(forms.Form):
    notify_email = forms.EmailField()


def send_error_email(error_message):
    if 'EMAIL_PASSWORD' in os.environ:
        msg = MIMEMultipart()
        password = os.environ['EMAIL_PASSWORD']
        msg['From'] = "talkingscores@gmail.com"
        msg['To'] = "talkingscores@gmail.com"
        msg['Subject'] = "Talking Scores Error"

        msg.attach(MIMEText(error_message, 'plain'))
        server = smtplib.SMTP('smtp.gmail.com: 587')
        server.starttls()
        server.login(msg['From'], password)
        server.sendmail(msg['From'], msg['To'], msg.as_string())
        server.quit()


def process(request, id, filename):
    template = loader.get_template('processing.html')
    context = {'id': id, 'filename': filename}
    return HttpResponse(template.render(context, request))


def score(request, id, filename):
    score_obj = TSScore(id=id, filename=filename)

    if score_obj.state() == TSScoreState.AWAITING_OPTIONS:
        return redirect('options', id, filename)
    elif score_obj.state() == TSScoreState.FETCHING:
        messages.error(request, "The requested score could not be found. It may have expired.")
        return redirect('index')
    else:
        try:
            html = score_obj.html()
            
            # Inject the id and filename variables by replacing the template placeholders
            # Use more specific replacement to avoid accidental matches
            download_url = f'/download_standalone/{id}/{filename}'
            html = html.replace(
                'href="/download_standalone/{{ id }}/{{ filename }}"',
                f'href="{download_url}"'
            )
            
            return HttpResponse(html)
        except Exception:
            logger.exception("Unable to process score: http://%s%s " % (request.get_host(), reverse('score', args=[id, filename])))
            return redirect('error', id, filename)


def midi(request, id, filename):
    mh = MidiHandler(request, id, filename)
    
    midi_file_path = mh.get_or_make_midi_file()
    
    if os.path.exists(midi_file_path):
        fr = FileResponse(open(midi_file_path, "rb"))
        fr['Access-Control-Allow-Origin'] = '*'
        fr['X-Robots-Tag'] = "noindex"
        return fr
    else:
        logger.error(f"MIDI file not found at path: {midi_file_path}")
        return HttpResponse("MIDI file not found.", status=404)


def error(request, id, filename):
    if request.method == 'POST':
        form = NotifyEmailForm(request.POST)
        if form.is_valid():
            notification_message = "Notifications about score http://%s%s should go to %s" % (
                request.get_host(), reverse('score', args=[id, filename]), form.cleaned_data['notify_email'])
            logger.error(notification_message)
            send_error_email(notification_message)
        else:
            logger.warn(str(form.errors))
    else:
        form = NotifyEmailForm()

    template = loader.get_template('error.html')
    context = {'id': id, 'filename': filename, 'form': form}
    return HttpResponse(template.render(context, request))


def change_log(request):
    template = loader.get_template('change-log.html')
    context = {}
    return HttpResponse(template.render(context, request))


def contact_us(request):
    template = loader.get_template('contact-us.html')
    context = {}
    return HttpResponse(template.render(context, request))


def privacy_policy(request):
    template = loader.get_template('privacy-policy.html')
    context = {}
    return HttpResponse(template.render(context, request))


def options(request, id, filename):
    ACCESSIBLE_PALETTE = [
        '#E6194B',  # Red
        '#3CB44B',  # Green
        '#4363D8',  # Blue
        '#F58231',  # Orange
        '#911EB4',  # Purple
        '#46F0F0',  # Cyan
        '#FABEBE',  # Pink
        '#008080',  # Teal
        '#F032E6',  # Magenta
        '#FFE119',  # Yellow
        '#BFEF45',  # Lime
        '#9A6324',  # Brown
    ]
    try:
        score_obj = TSScore(id=id, filename=filename)
        data_path = score_obj.get_data_file_path()
        options_path = data_path + '.opts'
        logger.info("Reading score %s" % data_path)
        score_info = score_obj.info()
    except Exception:
        logger.exception("Unable to process score (before options screen!): http://%s%s " % (request.get_host(), reverse('score', args=[id, filename])))
        return redirect('error', id, filename)

    if request.method == 'POST':
        instruments = [int(i) for i in request.POST.getlist("instruments")]

        if not instruments:
            form = TalkingScoreGenerationOptionsForm(request.POST)
            form.add_error(None, "Please select at least one instrument to describe.")
            if score_info.get('rhythm_range'):
                rhythms_with_colors = []
                for i, rhythm_name in enumerate(score_info['rhythm_range']):
                    default_color = ACCESSIBLE_PALETTE[i % len(ACCESSIBLE_PALETTE)]
                    rhythms_with_colors.append({
                        'name': rhythm_name,
                        'id_name': slugify(rhythm_name),
                        'default_color': default_color
                    })
                score_info['rhythm_range'] = rhythms_with_colors
            context = {'form': form, 'score_info': score_info}
            return render(request, 'options.html', context)

        color_profiles = {
            "default": {"C": "#FF0000", "D": "#A52A2A", "E": "#808080", "F": "#0000FF", "G": "#000000", "A": "#FFFF00", "B": "#008000"},
            "classic": {"C": "#FF0000", "D": "#FFA500", "E": "#FFFF00", "F": "#008000", "G": "#0000FF", "A": "#4B0082", "B": "#EE82EE"}
        }
        selected_profile = request.POST.get("colorProfile", "default")
        figure_note_colours = {}
        if selected_profile == "custom":
            figure_note_colours = {key.split('_')[1]: val for key, val in request.POST.items() if key.startswith('color_') and not key.startswith('color_rhythm_') and not key.startswith('color_octave_')}
        else:
            figure_note_colours = color_profiles.get(selected_profile, {})

        options_data = {
            "bars_at_a_time": int(request.POST.get("bars_at_a_time", 2)),
            "beat_division": request.POST.get("beat_division"),
            "play_all": "chk_playAll" in request.POST,
            "play_selected": "chk_playSelected" in request.POST,
            "play_unselected": "chk_playUnselected" in request.POST,
            "instruments": [int(i) for i in request.POST.getlist("instruments")],
            "pitch_description": request.POST.get("pitch_description", "noteName"),
            "rhythm_description": request.POST.get("rhythm_description", "british"),
            "dot_position": request.POST.get("dot_position", "before"),
            "rhythm_announcement": request.POST.get("rhythm_announcement", "onChange"),
            "octave_description": request.POST.get("octave_description", "name"),
            "octave_position": request.POST.get("octave_position", "before"),
            "octave_announcement": request.POST.get("octave_announcement", "onChange"),
            "include_rests": "chk_include_rests" in request.POST,
            "include_ties": "chk_include_ties" in request.POST,
            "include_arpeggios": "chk_include_arpeggios" in request.POST,
            "describe_chords": "chk_describe_chords" in request.POST,
            "include_dynamics": "chk_include_dynamics" in request.POST,
            "accidental_style": request.POST.get("accidental_style", "words"),
            "repetition_mode": request.POST.get("repetition_mode", "learning"),
            "colour_position": request.POST.get("colour_style", "none"),
            "colour_pitch": "chk_colourPitch" in request.POST,
            "rhythm_colour_mode": request.POST.get("rhythm_colour_mode", "none"),
            "octave_colour_mode": request.POST.get("octave_colour_mode", "none"),
            "key_signature_accidentals": request.POST.get("key_signature_accidentals", "applied"),
            "advanced_rhythm_colours": {slugify(key.replace('color_rhythm_', '')): value for key, value in request.POST.items() if key.startswith('color_rhythm_')},
            "advanced_octave_colours": {key.replace('color_octave_', ''): value for key, value in request.POST.items() if key.startswith('color_octave_')},
            "figureNoteColours": figure_note_colours
        }

        with open(options_path, "w") as options_fh:
            json.dump(options_data, options_fh)

        return redirect('process', id, filename)

    else:
        if score_info.get('rhythm_range'):
            rhythms_with_colors = []
            for i, rhythm_name in enumerate(score_info['rhythm_range']):
                default_color = ACCESSIBLE_PALETTE[i % len(ACCESSIBLE_PALETTE)]
                rhythms_with_colors.append({
                    'name': rhythm_name,
                    'id_name': slugify(rhythm_name),
                    'default_color': default_color
                })
            score_info['rhythm_range'] = rhythms_with_colors

        form = TalkingScoreGenerationOptionsForm()
        context = {'form': form, 'score_info': score_info}
        return render(request, 'options.html', context)


def index(request):
    if request.method == 'POST':
        form = MusicXMLSubmissionForm(request.POST, request.FILES)
        
        if form.is_valid():
            try:
                score = None
                uploaded_file = form.cleaned_data.get('filename')
                url = form.cleaned_data.get('url')

                if uploaded_file:
                    uploaded_file.seek(0)
                    score = TSScore.from_uploaded_file(uploaded_file)
                elif url:
                    score = TSScore.from_url(url)
                
                if score:
                    return redirect('score', id=score.id, filename=score.filename)

            except Exception as ex:
                error_message = "The MusicXML file could not be processed. Please ensure it is a valid MusicXML file and try again."
                logger.error(f"File Processing Error: {ex}", exc_info=True)
                messages.error(request, error_message)
                return redirect('index')
        else:
            for field, error_list in form.errors.items():
                for error in error_list:
                    messages.error(request, error)
            return redirect('index')

    else:
        form = MusicXMLSubmissionForm()

    example_scores = [f for f in os.listdir(os.path.join(BASE_DIR, 'talkingscoresapp', 'static', 'data')) if f.endswith('.html')]
    context = {'form': form, 'example_scores': example_scores}
    return render(request, 'index.html', context)